// GENERATED by web/scripts/gen-demo-abis.mjs from contracts/out — do commit; regenerate after
// contract ABI changes (`node web/scripts/gen-demo-abis.mjs`). CI runs it with `--check`.
// Demo mode only (ADR-0016): never imported outside `web/src/demo/`.
export const DEMO_ABIS = {
  "AdSlot": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "indexed": true,
          "name": "owner",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "width",
          "type": "uint16"
        },
        {
          "indexed": false,
          "name": "height",
          "type": "uint16"
        },
        {
          "indexed": false,
          "name": "kind",
          "type": "uint8"
        },
        {
          "indexed": false,
          "name": "domain",
          "type": "string"
        }
      ],
      "name": "SlotMinted",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "version",
          "type": "uint32"
        },
        {
          "indexed": false,
          "name": "period_seconds",
          "type": "uint64"
        },
        {
          "indexed": false,
          "name": "first_period_start",
          "type": "uint64"
        }
      ],
      "name": "CalendarSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "indexed": true,
          "name": "period_index",
          "type": "uint256"
        },
        {
          "indexed": true,
          "name": "user",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "version",
          "type": "uint32"
        },
        {
          "indexed": false,
          "name": "start",
          "type": "uint64"
        },
        {
          "indexed": false,
          "name": "end",
          "type": "uint64"
        },
        {
          "indexed": false,
          "name": "creative_id",
          "type": "uint256"
        }
      ],
      "name": "LeaseSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "market",
          "type": "address"
        }
      ],
      "name": "MarketSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "base_uri",
          "type": "string"
        }
      ],
      "name": "BaseURISet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "previous_owner",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "new_owner",
          "type": "address"
        }
      ],
      "name": "OwnershipTransferred",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "minter",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "status",
          "type": "bool"
        }
      ],
      "name": "RoleMinterChanged",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "sender",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "receiver",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "token_id",
          "type": "uint256"
        }
      ],
      "name": "Transfer",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "owner",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "approved",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "token_id",
          "type": "uint256"
        }
      ],
      "name": "Approval",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "owner",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "operator",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "approved",
          "type": "bool"
        }
      ],
      "name": "ApprovalForAll",
      "type": "event"
    },
    {
      "inputs": [
        {
          "name": "interface_id",
          "type": "bytes4"
        }
      ],
      "name": "supportsInterface",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "owner",
          "type": "address"
        }
      ],
      "name": "balanceOf",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "token_id",
          "type": "uint256"
        }
      ],
      "name": "ownerOf",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "token_id",
          "type": "uint256"
        }
      ],
      "name": "getApproved",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "arg0",
          "type": "address"
        },
        {
          "name": "arg1",
          "type": "address"
        }
      ],
      "name": "isApprovedForAll",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "owner",
          "type": "address"
        },
        {
          "name": "to",
          "type": "address"
        },
        {
          "name": "token_id",
          "type": "uint256"
        }
      ],
      "name": "transferFrom",
      "outputs": [],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "owner",
          "type": "address"
        },
        {
          "name": "to",
          "type": "address"
        },
        {
          "name": "token_id",
          "type": "uint256"
        }
      ],
      "name": "safeTransferFrom",
      "outputs": [],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "owner",
          "type": "address"
        },
        {
          "name": "to",
          "type": "address"
        },
        {
          "name": "token_id",
          "type": "uint256"
        },
        {
          "name": "data",
          "type": "bytes"
        }
      ],
      "name": "safeTransferFrom",
      "outputs": [],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "to",
          "type": "address"
        },
        {
          "name": "token_id",
          "type": "uint256"
        }
      ],
      "name": "approve",
      "outputs": [],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "operator",
          "type": "address"
        },
        {
          "name": "approved",
          "type": "bool"
        }
      ],
      "name": "setApprovalForAll",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "totalSupply",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "index",
          "type": "uint256"
        }
      ],
      "name": "tokenByIndex",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "owner",
          "type": "address"
        },
        {
          "name": "index",
          "type": "uint256"
        }
      ],
      "name": "tokenOfOwnerByIndex",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "name",
      "outputs": [
        {
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "symbol",
      "outputs": [
        {
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "owner",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "new_owner",
          "type": "address"
        }
      ],
      "name": "transfer_ownership",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "renounce_ownership",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "components": [
            {
              "name": "width",
              "type": "uint16"
            },
            {
              "name": "height",
              "type": "uint16"
            },
            {
              "name": "kind",
              "type": "uint8"
            },
            {
              "name": "domain",
              "type": "string"
            }
          ],
          "name": "spec",
          "type": "tuple"
        }
      ],
      "name": "mint_slot",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "name": "period_seconds",
          "type": "uint64"
        },
        {
          "name": "first_period_start",
          "type": "uint64"
        }
      ],
      "name": "set_calendar",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "name": "period_index",
          "type": "uint256"
        },
        {
          "name": "user",
          "type": "address"
        },
        {
          "name": "creative_id",
          "type": "uint256"
        }
      ],
      "name": "set_lease",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "market",
          "type": "address"
        }
      ],
      "name": "set_market",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "base_uri",
          "type": "string"
        }
      ],
      "name": "set_base_uri",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "token_id",
          "type": "uint256"
        }
      ],
      "name": "tokenURI",
      "outputs": [
        {
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        }
      ],
      "name": "spec_of",
      "outputs": [
        {
          "components": [
            {
              "name": "width",
              "type": "uint16"
            },
            {
              "name": "height",
              "type": "uint16"
            },
            {
              "name": "kind",
              "type": "uint8"
            },
            {
              "name": "domain",
              "type": "string"
            }
          ],
          "name": "",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        }
      ],
      "name": "calendar_of",
      "outputs": [
        {
          "components": [
            {
              "name": "version",
              "type": "uint32"
            },
            {
              "name": "period_seconds",
              "type": "uint64"
            },
            {
              "name": "first_period_start",
              "type": "uint64"
            }
          ],
          "name": "",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        }
      ],
      "name": "last_leased_end_of",
      "outputs": [
        {
          "name": "",
          "type": "uint64"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "name": "period_index",
          "type": "uint256"
        }
      ],
      "name": "period_window",
      "outputs": [
        {
          "name": "",
          "type": "uint64"
        },
        {
          "name": "",
          "type": "uint64"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        }
      ],
      "name": "current_period",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        },
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "name": "period_index",
          "type": "uint256"
        }
      ],
      "name": "lease_of",
      "outputs": [
        {
          "components": [
            {
              "name": "user",
              "type": "address"
            },
            {
              "name": "creative_id",
              "type": "uint256"
            }
          ],
          "name": "",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "tokenId",
          "type": "uint256"
        }
      ],
      "name": "userOf",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "tokenId",
          "type": "uint256"
        }
      ],
      "name": "userExpires",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "market",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "base_uri",
      "outputs": [
        {
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "Marketplace": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "start_price",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "floor_price",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "lead_seconds",
          "type": "uint64"
        },
        {
          "indexed": false,
          "name": "sale_end",
          "type": "uint64"
        },
        {
          "indexed": false,
          "name": "approval_mode",
          "type": "uint8"
        },
        {
          "indexed": false,
          "name": "sale_mode",
          "type": "uint8"
        },
        {
          "indexed": false,
          "name": "floor_cpc",
          "type": "uint256"
        }
      ],
      "name": "TermsSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "vault",
          "type": "address"
        }
      ],
      "name": "CampaignVaultSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "paused",
          "type": "bool"
        }
      ],
      "name": "PausedSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "indexed": true,
          "name": "period_index",
          "type": "uint256"
        },
        {
          "indexed": true,
          "name": "buyer",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "publisher",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "creative_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "price",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "fee",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "approval_mode",
          "type": "uint8"
        },
        {
          "indexed": false,
          "name": "start",
          "type": "uint64"
        },
        {
          "indexed": false,
          "name": "end",
          "type": "uint64"
        }
      ],
      "name": "Purchased",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "fee_bps",
          "type": "uint16"
        }
      ],
      "name": "FeeSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "treasury",
          "type": "address"
        }
      ],
      "name": "TreasurySet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "previous_owner",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "new_owner",
          "type": "address"
        }
      ],
      "name": "OwnershipTransferred",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "owner",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "new_owner",
          "type": "address"
        }
      ],
      "name": "transfer_ownership",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "renounce_ownership",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "name": "start_price",
          "type": "uint256"
        },
        {
          "name": "floor_price",
          "type": "uint256"
        },
        {
          "name": "lead_seconds",
          "type": "uint64"
        },
        {
          "name": "sale_end",
          "type": "uint64"
        },
        {
          "name": "approval_mode",
          "type": "uint8"
        },
        {
          "name": "sale_mode",
          "type": "uint8"
        },
        {
          "name": "floor_cpc",
          "type": "uint256"
        }
      ],
      "name": "set_terms",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "name": "paused",
          "type": "bool"
        }
      ],
      "name": "set_paused",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "name": "period_index",
          "type": "uint256"
        },
        {
          "name": "creative_id",
          "type": "uint256"
        },
        {
          "name": "max_price",
          "type": "uint256"
        }
      ],
      "name": "buy",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "name": "period_index",
          "type": "uint256"
        },
        {
          "name": "creative_id",
          "type": "uint256"
        },
        {
          "name": "max_price",
          "type": "uint256"
        },
        {
          "name": "deadline",
          "type": "uint256"
        },
        {
          "name": "v",
          "type": "uint8"
        },
        {
          "name": "r",
          "type": "bytes32"
        },
        {
          "name": "s",
          "type": "bytes32"
        }
      ],
      "name": "buy_with_permit",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "fee_bps",
          "type": "uint16"
        }
      ],
      "name": "set_fee_bps",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "treasury",
          "type": "address"
        }
      ],
      "name": "set_treasury",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "vault",
          "type": "address"
        }
      ],
      "name": "set_campaign_vault",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        }
      ],
      "name": "terms_of",
      "outputs": [
        {
          "components": [
            {
              "name": "start_price",
              "type": "uint256"
            },
            {
              "name": "floor_price",
              "type": "uint256"
            },
            {
              "name": "lead_seconds",
              "type": "uint64"
            },
            {
              "name": "sale_end",
              "type": "uint64"
            },
            {
              "name": "approval_mode",
              "type": "uint8"
            },
            {
              "name": "sale_mode",
              "type": "uint8"
            },
            {
              "name": "floor_cpc",
              "type": "uint256"
            },
            {
              "name": "paused",
              "type": "bool"
            }
          ],
          "name": "",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "name": "period_index",
          "type": "uint256"
        }
      ],
      "name": "price",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "name": "period_index",
          "type": "uint256"
        }
      ],
      "name": "quote",
      "outputs": [
        {
          "components": [
            {
              "name": "sellable",
              "type": "bool"
            },
            {
              "name": "reason",
              "type": "string"
            },
            {
              "name": "price",
              "type": "uint256"
            },
            {
              "name": "fee",
              "type": "uint256"
            },
            {
              "name": "open_at",
              "type": "uint64"
            },
            {
              "name": "start",
              "type": "uint64"
            },
            {
              "name": "end",
              "type": "uint64"
            }
          ],
          "name": "",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "USDC",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "AD_SLOT",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "REGISTRY",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "fee_bps",
      "outputs": [
        {
          "name": "",
          "type": "uint16"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "treasury",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "campaign_vault",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "CreativeRegistry": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "creative_id",
          "type": "uint256"
        },
        {
          "indexed": true,
          "name": "advertiser",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "kind",
          "type": "uint8"
        },
        {
          "indexed": false,
          "name": "content_hash",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "name": "uri",
          "type": "string"
        },
        {
          "indexed": false,
          "name": "mime",
          "type": "string"
        },
        {
          "indexed": false,
          "name": "width",
          "type": "uint16"
        },
        {
          "indexed": false,
          "name": "height",
          "type": "uint16"
        },
        {
          "indexed": false,
          "name": "click_url",
          "type": "string"
        }
      ],
      "name": "CreativeRegistered",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "creative_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "nft_chain_id",
          "type": "uint64"
        },
        {
          "indexed": false,
          "name": "nft_contract",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "nft_token_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "nft_standard",
          "type": "uint8"
        }
      ],
      "name": "NftCreativeRegistered",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "publisher",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "creative_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "advertiser",
          "type": "address"
        }
      ],
      "name": "ApprovalRequested",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "publisher",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "creative_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "status",
          "type": "uint8"
        }
      ],
      "name": "ApprovalSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "publisher",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "advertiser",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "allowed",
          "type": "bool"
        }
      ],
      "name": "AdvertiserAllowed",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "creative_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "by",
          "type": "address"
        }
      ],
      "name": "CreativeRevoked",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "moderator",
          "type": "address"
        }
      ],
      "name": "ModeratorSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "previous_owner",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "new_owner",
          "type": "address"
        }
      ],
      "name": "OwnershipTransferred",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "owner",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "new_owner",
          "type": "address"
        }
      ],
      "name": "transfer_ownership",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "renounce_ownership",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "uri",
          "type": "string"
        },
        {
          "name": "content_hash",
          "type": "bytes32"
        },
        {
          "name": "mime",
          "type": "string"
        },
        {
          "name": "width",
          "type": "uint16"
        },
        {
          "name": "height",
          "type": "uint16"
        },
        {
          "name": "click_url",
          "type": "string"
        }
      ],
      "name": "register_media",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "nft_chain_id",
          "type": "uint64"
        },
        {
          "name": "nft_contract",
          "type": "address"
        },
        {
          "name": "nft_token_id",
          "type": "uint256"
        },
        {
          "name": "nft_standard",
          "type": "uint8"
        },
        {
          "name": "click_url",
          "type": "string"
        }
      ],
      "name": "register_nft",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "publisher",
          "type": "address"
        },
        {
          "name": "creative_id",
          "type": "uint256"
        }
      ],
      "name": "request_approval",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "creative_id",
          "type": "uint256"
        },
        {
          "name": "approved",
          "type": "bool"
        }
      ],
      "name": "set_approval",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "creative_id",
          "type": "uint256"
        }
      ],
      "name": "revoke_approval",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "advertiser",
          "type": "address"
        },
        {
          "name": "allowed",
          "type": "bool"
        }
      ],
      "name": "set_advertiser_allowed",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "creative_id",
          "type": "uint256"
        }
      ],
      "name": "moderator_revoke",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "moderator",
          "type": "address"
        }
      ],
      "name": "set_moderator",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "creative_id",
          "type": "uint256"
        }
      ],
      "name": "get_creative",
      "outputs": [
        {
          "components": [
            {
              "name": "advertiser",
              "type": "address"
            },
            {
              "name": "kind",
              "type": "uint8"
            },
            {
              "name": "uri",
              "type": "string"
            },
            {
              "name": "content_hash",
              "type": "bytes32"
            },
            {
              "name": "mime",
              "type": "string"
            },
            {
              "name": "width",
              "type": "uint16"
            },
            {
              "name": "height",
              "type": "uint16"
            },
            {
              "name": "click_url",
              "type": "string"
            },
            {
              "name": "nft_chain_id",
              "type": "uint64"
            },
            {
              "name": "nft_contract",
              "type": "address"
            },
            {
              "name": "nft_token_id",
              "type": "uint256"
            },
            {
              "name": "nft_standard",
              "type": "uint8"
            },
            {
              "name": "revoked",
              "type": "bool"
            }
          ],
          "name": "",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "creative_id",
          "type": "uint256"
        }
      ],
      "name": "is_active",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "publisher",
          "type": "address"
        },
        {
          "name": "creative_id",
          "type": "uint256"
        }
      ],
      "name": "is_blocked_for",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "publisher",
          "type": "address"
        },
        {
          "name": "creative_id",
          "type": "uint256"
        }
      ],
      "name": "is_approved_for",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "publisher",
          "type": "address"
        },
        {
          "name": "creative_id",
          "type": "uint256"
        }
      ],
      "name": "approval_status",
      "outputs": [
        {
          "name": "",
          "type": "uint8"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "publisher",
          "type": "address"
        },
        {
          "name": "advertiser",
          "type": "address"
        }
      ],
      "name": "is_advertiser_allowed",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "next_id",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "moderator",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "CampaignVault": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "campaign_id",
          "type": "uint256"
        },
        {
          "indexed": true,
          "name": "advertiser",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "creative_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "max_cpc",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "budget",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "valid_from",
          "type": "uint64"
        },
        {
          "indexed": false,
          "name": "valid_until",
          "type": "uint64"
        }
      ],
      "name": "CampaignOpened",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "campaign_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "amount",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "remaining",
          "type": "uint256"
        }
      ],
      "name": "CampaignToppedUp",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "campaign_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "max_cpc",
          "type": "uint256"
        }
      ],
      "name": "MaxCpcSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "campaign_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "paused",
          "type": "bool"
        }
      ],
      "name": "CampaignPausedSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "campaign_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "close_after",
          "type": "uint64"
        }
      ],
      "name": "CloseRequested",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "campaign_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "refund",
          "type": "uint256"
        }
      ],
      "name": "CampaignFinalized",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "campaign_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "publisher",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "payable_clicks",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "charged",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "fee",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "batch_id",
          "type": "bytes32"
        }
      ],
      "name": "Settled",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "settler",
          "type": "address"
        }
      ],
      "name": "SettlerSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "fee_bps",
          "type": "uint16"
        }
      ],
      "name": "VaultFeeSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "treasury",
          "type": "address"
        }
      ],
      "name": "VaultTreasurySet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "seconds",
          "type": "uint64"
        }
      ],
      "name": "CloseDelaySet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "max_batch_charge",
          "type": "uint256"
        }
      ],
      "name": "MaxBatchChargeSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "previous_owner",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "new_owner",
          "type": "address"
        }
      ],
      "name": "OwnershipTransferred",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "owner",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "new_owner",
          "type": "address"
        }
      ],
      "name": "transfer_ownership",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "renounce_ownership",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "name": "creative_id",
          "type": "uint256"
        },
        {
          "name": "max_cpc",
          "type": "uint256"
        },
        {
          "name": "budget",
          "type": "uint256"
        },
        {
          "name": "valid_from",
          "type": "uint64"
        },
        {
          "name": "valid_until",
          "type": "uint64"
        }
      ],
      "name": "open_campaign",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        },
        {
          "name": "creative_id",
          "type": "uint256"
        },
        {
          "name": "max_cpc",
          "type": "uint256"
        },
        {
          "name": "budget",
          "type": "uint256"
        },
        {
          "name": "valid_from",
          "type": "uint64"
        },
        {
          "name": "valid_until",
          "type": "uint64"
        },
        {
          "name": "deadline",
          "type": "uint256"
        },
        {
          "name": "v",
          "type": "uint8"
        },
        {
          "name": "r",
          "type": "bytes32"
        },
        {
          "name": "s",
          "type": "bytes32"
        }
      ],
      "name": "open_campaign_with_permit",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "campaign_id",
          "type": "uint256"
        },
        {
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "top_up",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "campaign_id",
          "type": "uint256"
        },
        {
          "name": "amount",
          "type": "uint256"
        },
        {
          "name": "deadline",
          "type": "uint256"
        },
        {
          "name": "v",
          "type": "uint8"
        },
        {
          "name": "r",
          "type": "bytes32"
        },
        {
          "name": "s",
          "type": "bytes32"
        }
      ],
      "name": "top_up_with_permit",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "campaign_id",
          "type": "uint256"
        },
        {
          "name": "max_cpc",
          "type": "uint256"
        }
      ],
      "name": "set_max_cpc",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "campaign_id",
          "type": "uint256"
        },
        {
          "name": "paused",
          "type": "bool"
        }
      ],
      "name": "set_paused",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "campaign_id",
          "type": "uint256"
        }
      ],
      "name": "request_close",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "campaign_id",
          "type": "uint256"
        }
      ],
      "name": "finalize_close",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "campaign_id",
          "type": "uint256"
        },
        {
          "name": "payable_clicks",
          "type": "uint256"
        },
        {
          "name": "charged_usdc",
          "type": "uint256"
        },
        {
          "name": "batch_id",
          "type": "bytes32"
        }
      ],
      "name": "settle_batch",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "settler",
          "type": "address"
        }
      ],
      "name": "set_settler",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "fee_bps",
          "type": "uint16"
        }
      ],
      "name": "set_fee_bps",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "treasury",
          "type": "address"
        }
      ],
      "name": "set_treasury",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "seconds",
          "type": "uint64"
        }
      ],
      "name": "set_close_delay",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "max_batch_charge",
          "type": "uint256"
        }
      ],
      "name": "set_max_batch_charge",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "campaign_id",
          "type": "uint256"
        }
      ],
      "name": "campaign_of",
      "outputs": [
        {
          "components": [
            {
              "name": "advertiser",
              "type": "address"
            },
            {
              "name": "slot_id",
              "type": "uint256"
            },
            {
              "name": "creative_id",
              "type": "uint256"
            },
            {
              "name": "max_cpc",
              "type": "uint256"
            },
            {
              "name": "remaining",
              "type": "uint256"
            },
            {
              "name": "valid_from",
              "type": "uint64"
            },
            {
              "name": "valid_until",
              "type": "uint64"
            },
            {
              "name": "paused",
              "type": "bool"
            },
            {
              "name": "close_after",
              "type": "uint64"
            },
            {
              "name": "closed",
              "type": "bool"
            }
          ],
          "name": "",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "slot_id",
          "type": "uint256"
        }
      ],
      "name": "open_campaigns_of",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "batch_id",
          "type": "bytes32"
        }
      ],
      "name": "used_batch",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "USDC",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "AD_SLOT",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "REGISTRY",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "MARKETPLACE",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "settler",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "fee_bps",
      "outputs": [
        {
          "name": "",
          "type": "uint16"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "treasury",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "close_delay_seconds",
      "outputs": [
        {
          "name": "",
          "type": "uint64"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "max_batch_charge",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "campaign_count",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "USDC": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "previous_owner",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "new_owner",
          "type": "address"
        }
      ],
      "name": "OwnershipTransferred",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "minter",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "status",
          "type": "bool"
        }
      ],
      "name": "RoleMinterChanged",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "sender",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "receiver",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "value",
          "type": "uint256"
        }
      ],
      "name": "Transfer",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "owner",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "spender",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "value",
          "type": "uint256"
        }
      ],
      "name": "Approval",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "totalSupply",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "arg0",
          "type": "address"
        }
      ],
      "name": "balanceOf",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "arg0",
          "type": "address"
        },
        {
          "name": "arg1",
          "type": "address"
        }
      ],
      "name": "allowance",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "to",
          "type": "address"
        },
        {
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "transfer",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "owner",
          "type": "address"
        },
        {
          "name": "to",
          "type": "address"
        },
        {
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "transferFrom",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "spender",
          "type": "address"
        },
        {
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "approve",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "name",
      "outputs": [
        {
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "symbol",
      "outputs": [
        {
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "decimals",
      "outputs": [
        {
          "name": "",
          "type": "uint8"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "owner",
          "type": "address"
        },
        {
          "name": "spender",
          "type": "address"
        },
        {
          "name": "amount",
          "type": "uint256"
        },
        {
          "name": "deadline",
          "type": "uint256"
        },
        {
          "name": "v",
          "type": "uint8"
        },
        {
          "name": "r",
          "type": "bytes32"
        },
        {
          "name": "s",
          "type": "bytes32"
        }
      ],
      "name": "permit",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "arg0",
          "type": "address"
        }
      ],
      "name": "nonces",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "DOMAIN_SEPARATOR",
      "outputs": [
        {
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "owner",
          "type": "address"
        },
        {
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "mint",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "minter",
          "type": "address"
        },
        {
          "name": "status",
          "type": "bool"
        }
      ],
      "name": "set_minter",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "owner",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ]
} as const;
